version: 2

runOnDocker: &runOnDocker
  working_directory: ~/mesg-cli
  docker:
    - image: circleci/node:10.16

jobs:
  test:
    <<: *runOnDocker
    steps:
      - checkout
      - run: ls
      - run: npm install
      - run: npm run build
      - run: npm test

workflows:
  version: 2

  test_commit:
    jobs:
      - test